### ISSUE TITLE
DB attribute

### ISSUE THREAD

**Issue by DevJihun** [SKKU-aid/aid-backend#5]
## Attribute 종류

- 학과
- 학점
- 학기
- 장학금 topic
- 나이
- 지역
- 소득분위
- 신청기간

---

추가해야 하거나 빼도 될 것 같은 속성이 있으면 알려주세요 :)

**Comment by DevJihun** [comment]
추가로 오늘 회의 때 이야기 한 내용입니다!

- atlas 이용해서 mongoDB 생성 후 작업하기

- [node.js에서 메일 전송하기 참고자료](https://velog.io/@josworks27/Back-end-Node.js%EC%97%90%EC%84%9C-%EB%A9%94%EC%9D%BC-%EC%A0%84%EC%86%A1%ED%95%98%EA%B8%B0-feat.-Nodemailer-Gmail)

**Comment by DevJihun** [comment]
<html>
<body><article id="939e8f2d-15d5-4f34-9d91-834a9159895f" class="page sans"><header><h1 class="page-title">DB table</h1><p class="page-description"></p></header><div class="page-body"><h2 id="0dc4d463-6e5d-4067-9dbc-1fac8ac076ca" class="">User table</h2><table id="77a00d12-f01f-4f32-9f5e-8718332da00b" class="simple-table"><thead class="simple-table-header"><tr id="2db04a0c-14f2-4ed0-8143-fb6ee4094346"><th id="miVR" class="simple-table-header-color simple-table-header" style="width:137.00000762939453px">Attribute</th><th id="tJFg" class="simple-table-header-color simple-table-header">Type</th><th id="boJT" class="simple-table-header-color simple-table-header">Description</th><th id="x\d^" class="simple-table-header-color simple-table-header" style="width:180.00000762939453px">Example</th><th id="dA?|" class="simple-table-header-color simple-table-header" style="width:246.72222900390625px">특이사항</th></tr></thead><tbody><tr id="d1152d77-df34-401f-a32e-55c7a919d86c"><td id="miVR" class="" style="width:137.00000762939453px">_id</td><td id="tJFg" class="">string</td><td id="boJT" class="">유저 id</td><td id="x\d^" class="" style="width:180.00000762939453px">“example@example.com”</td><td id="dA?|" class="" style="width:246.72222900390625px">고유값</td></tr><tr id="d81cc5d0-7890-4b9f-947c-aed9f7c410f8"><td id="miVR" class="" style="width:137.00000762939453px">userPassword</td><td id="tJFg" class="">string</td><td id="boJT" class="">유저 비밀번호</td><td id="x\d^" class="" style="width:180.00000762939453px">“password”</td><td id="dA?|" class="" style="width:246.72222900390625px"></td></tr><tr id="c32fa662-f22b-4561-adb3-59917f43f222"><td id="miVR" class="" style="width:137.00000762939453px">sex</td><td id="tJFg" class="">boolean</td><td id="boJT" class="">성별</td><td id="x\d^" class="" style="width:180.00000762939453px">true</td><td id="dA?|" class="" style="width:246.72222900390625px">남: true / 여: false</td></tr><tr id="8bdf95ea-ac55-467d-8491-1135b219b20e"><td id="miVR" class="" style="width:137.00000762939453px">birthday</td><td id="tJFg" class="">date</td><td id="boJT" class="">생년월일</td><td id="x\d^" class="" style="width:180.00000762939453px">2001-01-01</td><td id="dA?|" class="" style="width:246.72222900390625px">시간은 00:00:00으로 통일</td></tr><tr id="e0f47595-6d2b-4326-9d57-3fef711fec23"><td id="miVR" class="" style="width:137.00000762939453px">currentSemester</td><td id="tJFg" class="">number</td><td id="boJT" class="">현재 학기</td><td id="x\d^" class="" style="width:180.00000762939453px">4</td><td id="dA?|" class="" style="width:246.72222900390625px">9학기 이상은 9로 통일</td></tr><tr id="1c009152-5406-4ae2-b155-143aa3674e06"><td id="miVR" class="" style="width:137.00000762939453px">currentStatus</td><td id="tJFg" class="">number</td><td id="boJT" class="">학적 상태</td><td id="x\d^" class="" style="width:180.00000762939453px">“재학” / “휴학” / “졸업”</td><td id="dA?|" class="" style="width:246.72222900390625px"></td></tr><tr id="c8c79f2b-64a3-4bc2-9b84-b9e52182b1a7"><td id="miVR" class="" style="width:137.00000762939453px">incomeLevel</td><td id="tJFg" class="">number</td><td id="boJT" class="">소득분위</td><td id="x\d^" class="" style="width:180.00000762939453px">3</td><td id="dA?|" class="" style="width:246.72222900390625px">기초생활수급자일 경우 0</td></tr><tr id="702937f3-6a58-42b6-aa62-2418d9d7066b"><td id="miVR" class="" style="width:137.00000762939453px">lastGPA</td><td id="tJFg" class="">number</td><td id="boJT" class="">직전학기 평점</td><td id="x\d^" class="" style="width:180.00000762939453px">4.0</td><td id="dA?|" class="" style="width:246.72222900390625px"></td></tr><tr id="d8a715cf-9548-46fe-88a7-9d422f530740"><td id="miVR" class="" style="width:137.00000762939453px">totalGPA</td><td id="tJFg" class="">number</td><td id="boJT" class="">총 평균 평점</td><td id="x\d^" class="" style="width:180.00000762939453px">3.8</td><td id="dA?|" class="" style="width:246.72222900390625px"></td></tr><tr id="827c1094-9295-4ef0-bc05-4af5534d4fbb"><td id="miVR" class="" style="width:137.00000762939453px">major</td><td id="tJFg" class="">string</td><td id="boJT" class="">학과</td><td id="x\d^" class="" style="width:180.00000762939453px">“소프트웨어학과”</td><td id="dA?|" class="" style="width:246.72222900390625px">원전공 기준</td></tr><tr id="ffae8528-1cb2-47e2-973d-a141ba8b157f"><td id="miVR" class="" style="width:137.00000762939453px">region</td><td id="tJFg" class="">string</td><td id="boJT" class="">거주지</td><td id="x\d^" class="" style="width:180.00000762939453px">“서울”</td><td id="dA?|" class="" style="width:246.72222900390625px">도, 광역시, 특별시로 통일</td></tr><tr id="4edb1740-fa6a-408e-920f-f01a4049edcf"><td id="miVR" class="" style="width:137.00000762939453px">savedScholarship</td><td id="tJFg" class="">array (integer)</td><td id="boJT" class="">관심장학</td><td id="x\d^" class="" style="width:180.00000762939453px">[1, 3, 10]</td><td id="dA?|" class="" style="width:246.72222900390625px">scholarship의 _id 값으로 저장</td></tr></tbody></table><p id="62f5499d-d163-4891-96f5-caac88dca4ca" class="">
</p><h2 id="7feaf622-9437-4b2d-8cfe-05aa46214318" class="">Scholarship table</h2><table id="b075d1db-34d0-445e-ad48-710fd6208b44" class="simple-table"><thead class="simple-table-header"><tr id="f9831e3c-a701-4adf-8b88-fec711b4fbb1"><th id="&gt;Itv" class="simple-table-header-color simple-table-header" style="width:193px">Attribute</th><th id="&gt;&gt;Vh" class="simple-table-header-color simple-table-header">Type</th><th id="`|h~" class="simple-table-header-color simple-table-header" style="width:153.00003051757812px">Description</th><th id="vO&lt;p" class="simple-table-header-color simple-table-header" style="width:190.98611450195312px">Example</th><th id="_bHR" class="simple-table-header-color simple-table-header" style="width:257.00001525878906px">특이사항</th></tr></thead><tbody><tr id="79ac3dc2-1781-4dfe-98ce-63858086131f"><td id="&gt;Itv" class="" style="width:193px">_id</td><td id="&gt;&gt;Vh" class="">number</td><td id="`|h~" class="" style="width:153.00003051757812px">장학금 id</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">1</td><td id="_bHR" class="" style="width:257.00001525878906px">고유값</td></tr><tr id="802fdd92-3ff3-4eda-8137-b458edea96fc"><td id="&gt;Itv" class="" style="width:193px">scholarshipName</td><td id="&gt;&gt;Vh" class="">string</td><td id="`|h~" class="" style="width:153.00003051757812px">장학금 이름</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">“XX재단 장학금”</td><td id="_bHR" class="" style="width:257.00001525878906px"></td></tr><tr id="c2bbcd03-9c5f-4f99-a7d1-7b5c75a4a3e3"><td id="&gt;Itv" class="" style="width:193px">eligibleMajor</td><td id="&gt;&gt;Vh" class="">array (string)</td><td id="`|h~" class="" style="width:153.00003051757812px">지원 대상 학과</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">[”생명공학”, “화학공학”]</td><td id="_bHR" class="" style="width:257.00001525878906px">현재는 계열로 들어가 있음 (수정 예정)</td></tr><tr id="17cf2238-1b36-4b71-9b66-67e5492b44d6"><td id="&gt;Itv" class="" style="width:193px">minimumGPARequirement</td><td id="&gt;&gt;Vh" class="">number</td><td id="`|h~" class="" style="width:153.00003051757812px">최소 학점 기준</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">3.5 / null</td><td id="_bHR" class="" style="width:257.00001525878906px"></td></tr><tr id="1a210042-b97e-4f61-9148-483a0ffa984d"><td id="&gt;Itv" class="" style="width:193px">eligibleSemesters</td><td id="&gt;&gt;Vh" class="">array (number)</td><td id="`|h~" class="" style="width:153.00003051757812px">지원 가능 학기</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">[3, 4, 5, 6] / [-1]</td><td id="_bHR" class="" style="width:257.00001525878906px">대학원 재학생 대상일 경우 [-1]</td></tr><tr id="fc3780cf-16c3-407c-a559-741bb0f3491e"><td id="&gt;Itv" class="" style="width:193px">scholarshipType</td><td id="&gt;&gt;Vh" class="">string</td><td id="`|h~" class="" style="width:153.00003051757812px">장학금 유형</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">“성적 우수 장학금”</td><td id="_bHR" class="" style="width:257.00001525878906px"></td></tr><tr id="4f9dfcad-eb62-4281-8ac5-231da1b4cda6"><td id="&gt;Itv" class="" style="width:193px">ageLimit</td><td id="&gt;&gt;Vh" class="">number</td><td id="`|h~" class="" style="width:153.00003051757812px">나이 제한</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">30 / null</td><td id="_bHR" class="" style="width:257.00001525878906px"></td></tr><tr id="47ced0fc-ca00-4225-88a5-712162776f65"><td id="&gt;Itv" class="" style="width:193px">regionalRestrictions</td><td id="&gt;&gt;Vh" class="">array (string)</td><td id="`|h~" class="" style="width:153.00003051757812px">지역 제한</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">[”서울”, “수원”]</td><td id="_bHR" class="" style="width:257.00001525878906px"></td></tr><tr id="e601224d-cc72-4973-8efc-722cac5a5e50"><td id="&gt;Itv" class="" style="width:193px">incomeLevelRequirement</td><td id="&gt;&gt;Vh" class="">number</td><td id="`|h~" class="" style="width:153.00003051757812px">소득분위 기준</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">0 / 3 / null</td><td id="_bHR" class="" style="width:257.00001525878906px">기초생활수급자 대상일 경우 0</td></tr><tr id="2cf36ec2-09f4-43c1-be49-348131159cb8"><td id="&gt;Itv" class="" style="width:193px">applicationPeriod</td><td id="&gt;&gt;Vh" class="">string</td><td id="`|h~" class="" style="width:153.00003051757812px">신청 기간</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">2024-10-20 ~ 2024-10-31</td><td id="_bHR" class="" style="width:257.00001525878906px">신청 기간 시작일은 최종 수정일 기준</td></tr><tr id="0f63d200-6713-4530-bce0-e7b18aad062c"><td id="&gt;Itv" class="" style="width:193px">scholarshipAmount</td><td id="&gt;&gt;Vh" class="">string</td><td id="`|h~" class="" style="width:153.00003051757812px">장학금 금액</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">“2,000,000원”</td><td id="_bHR" class="" style="width:257.00001525878906px">string 형태로 변경</td></tr><tr id="bed0a540-ea2a-4a70-b93c-cd524027d263"><td id="&gt;Itv" class="" style="width:193px">numberOfRecipients</td><td id="&gt;&gt;Vh" class="">number</td><td id="`|h~" class="" style="width:153.00003051757812px">선발 인원</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">10 or null</td><td id="_bHR" class="" style="width:257.00001525878906px"></td></tr><tr id="368f55d3-4b09-462e-a1d6-9ffe826f2853"><td id="&gt;Itv" class="" style="width:193px">requiredDocumnets</td><td id="&gt;&gt;Vh" class="">array (string)</td><td id="`|h~" class="" style="width:153.00003051757812px">제출 서류</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">[”성적증명서”, “추천서”]</td><td id="_bHR" class="" style="width:257.00001525878906px"></td></tr><tr id="f299c9fc-ec52-44ad-9fb0-f4a64af8dab8"><td id="&gt;Itv" class="" style="width:193px">applicationMethod</td><td id="&gt;&gt;Vh" class="">string</td><td id="`|h~" class="" style="width:153.00003051757812px">신청 방법</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">&quot;메일 제출”</td><td id="_bHR" class="" style="width:257.00001525878906px"></td></tr><tr id="4fb271cc-2f65-418a-bf26-043347968f47"><td id="&gt;Itv" class="" style="width:193px">significnt</td><td id="&gt;&gt;Vh" class="">string</td><td id="`|h~" class="" style="width:153.00003051757812px">특이사항</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">&quot;XXX 행사 참석 필수”, “탈북민 대상 장학금”</td><td id="_bHR" class="" style="width:257.00001525878906px"></td></tr><tr id="d872fabe-4350-423e-9d44-782b2b9924f0"><td id="&gt;Itv" class="" style="width:193px">link</td><td id="&gt;&gt;Vh" class="">string</td><td id="`|h~" class="" style="width:153.00003051757812px">링크</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">“https://example.com”</td><td id="_bHR" class="" style="width:257.00001525878906px"></td></tr><tr id="e5561dda-3edf-4dff-bf9f-c260ae2c1f70"><td id="&gt;Itv" class="" style="width:193px">views</td><td id="&gt;&gt;Vh" class="">number</td><td id="`|h~" class="" style="width:153.00003051757812px">조회수</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">1234</td><td id="_bHR" class="" style="width:257.00001525878906px"></td></tr><tr id="0013f4b3-38da-4912-aca2-9e70003f764a"><td id="&gt;Itv" class="" style="width:193px">foundation</td><td id="&gt;&gt;Vh" class="">string</td><td id="`|h~" class="" style="width:153.00003051757812px">재단 이름</td><td id="vO&lt;p" class="" style="width:190.98611450195312px">&quot;XX 장학재단”</td><td id="_bHR" class="" style="width:257.00001525878906px"></td></tr></tbody></table></div></article><span class="sans" style="font-size:14px;padding-top:2em"></span></body></html>

**Comment by ohsj3781** [comment]
User table attribute 에 유저id(user ID)와 추천 장학금(recommanded Scholarship){장학금 ID로 이루어진 List}
, Scholarship table attritube에 장학금 ID(Scholarship ID) 추가 하면 좋을것 같습니다.

**Comment by DevJihun** [comment]
넵 감사합니다 :)

**Comment by DevJihun** [comment]
## DB attributes 변경점

### Scholarship table attribute 추가:
- 조회수 (views)
- 재단 이름 (foundation)

### 장학정보 가져오기 함수 변경점
- 관심 장학에 포함되어 있는지 확인하고 response 해줘야 함
- URL & request에 userID 추가
